#
# ensures that the environment variables 
# - AWS_ACCESS_KEY_ID
# - AWS_ACCESS_KEY_ID
# are set; fails otherwise
#
- name: get environment variable AWS_ACCESS_KEY_ID
  set_fact:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID')}}"

- name: ensure environment variable AWS_ACCESS_KEY_ID
  fail:
    msg: |
      Missing environment variable AWS_ACCESS_KEY_ID.
      Set it first, i.e.
      $ export AWS_ACCESS_KEY_ID=<your-access-key>
  when: AWS_ACCESS_KEY_ID == ""

- name: get environment variable AWS_SECRET_ACCESS_KEY
  set_fact:
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"

- name: ensure environment variable AWS_SECRET_ACCESS_KEY
  fail:
    msg: |
      Missing environment variable AWS_SECRET_ACCESS_KEY.
      Set it first, i.e.
      $ export AWS_SECRET_ACCESS_KEY=<your-access-key>
  when: AWS_SECRET_ACCESS_KEY == ""